CREATE DATABASE library;

USE library;


CREATE TABLE BOOK (
  ID        INT PRIMARY KEY AUTO_INCREMENT,
  AUTHOR    VARCHAR(100) UNIQUE NOT NULL,
  TITLE     VARCHAR(255)        NOT NULL,
  PAGES     INT                 NOT NULL,
  COVER_URL VARCHAR(255)
);

CREATE TABLE BOOK_PAGE (
  ID      INT PRIMARY KEY AUTO_INCREMENT,
  BOOK_ID INT  NOT NULL,
  NUMBER  INT  NOT NULL,
  CONTENT TEXT NOT NULL,
  FOREIGN KEY (BOOK_ID) references BOOK (ID)
);

